### ISSUE TITLE
Portal Login Issue 

### ISSUE THREAD

**Issue by prakashkborntowin** [pierrejoubert/D365Portals#1]
I tried to login using my D365 api URL got below issue,
The entity with a name = 'adx_website' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=True, IsLoadedInStagedContext = False, Timestamp=1879825, MinActiveRowVersion=1879825

Anyone can help me, please?

**Comment by pierrejoubert** [comment]
Hi Prakash,

I am assuming you have the ADX solutions installed?

It sounds like the entity isn't available. 

Best regards
Pierre Joubert
